version: '3'

services:
    client:
        build: ./ui
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - './ui:/ui'
            - /ui/node_modules
        working_dir: /ui
        links:
            - api
        networks:
          - edirect-network
    api:
        build: ./api
        restart: always
        ports:
            - '9000:9000'
        volumes:
            - './api:/api'
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
          - edirect-network
    mongodb:
        image: mongo
        container_name: edirect-db
        volumes:
            - './data:/data/db'
        ports:
            - '27017:27017'
        command: 'mongod --noauth'
        networks:
            - edirect-network
networks:
    edirect-network:
        driver: bridge
